### ISSUE TITLE
How To use redux ?

### ISSUE THREAD

**Issue by mostafa-raafat** [caplin/FlexLayout#116]
How to use Redux with different tabs ?
How to make communication between inner window and some outer window ?
Also when i go outer the outer tab still exist with empty content not like 
golden layout when you outer the tab disappear and back  again when you close.

**Comment by nealus** [comment]
A popout tab is rendered by the same JS runtime, so you can communicate with it in the same way as any other tab (directly calling methods/callbacks etc, so you should not need to change your logic for popouts), the only difference is that it's rendered into another window/document.
By design a popped out tab keeps a placeholder in the main layout.

**Comment by mostafa-raafat** [comment]
thank you i get redux working with inner and outer window 
How can i hide or close the place holder when i go outer and show it back when i go inner

**Comment by nealus** [comment]
Sorry, there is no way to hide the placeholder tab when it's popped out
