### ISSUE TITLE
Redux?

### ISSUE THREAD

**Issue by philipbjorge** [caplin/FlexLayout#17]
This looks like a lovely library -- I'm interested in using it in a redux application.

I'm relatively new to the react/redux space so am wondering if you had any thoughts -- What issues do you think I will run into leveraging this in redux? Can I have the layout state live in my store?

Thanks

**Comment by neb42** [comment]
I'm currently experimenting with this. I was thinking the Layout class would take some model json rather than a model. This would come from the redux store. 

Model currently has a commented out method called apply. This takes a model's json and an action, then return a new model json. I was thinking this could be used in the reducer and Actions can be dispatched as actions.

**Comment by Kafkalasch** [comment]
Hi, I just wondered if there is any progress on this?
