### ISSUE TITLE
Tab buttons rendering outside tab bar when overflow

### ISSUE THREAD

**Issue by edemaine** [caplin/FlexLayout#195]
I'm trying to update [my app](https://github.com/edemaine/comingle) from an older version to the current version.  I'm finding that TabSets with an overflow button render the tab buttons too far left (via `style: {left: position}`), ending up outside the tab bar (clipping), and leaving a corresponding amount of blank space to the right.

Here's an example, where both tabs are supposed to be titled "New Tab".  The left TabSet has a single tab so no overflow, while the right TabSet has three tabs and overflows:

![image](https://user-images.githubusercontent.com/2218736/113215782-633ad500-9249-11eb-9af1-8e3a1235abe5.png)

Perhaps it's caused by my custom `+` button?  I'm adding it in `onRenderTabSet` by appending to `buttons`.

This used to work fine.  The use of negative `left` style seems to be new; what problem did it solve?

**Comment by nealus** [comment]
The previous tabs behaviour rendered the tabs left to right and set the last tab to the one selected from the overflow menu:

tabs    | overflow menu
1,2,3,4 | 5,6,7

selecting 6 from overflow menu would give:

1,2,3,6 | 4,5,7  

selecting 3 would then give

1,2,3,4 | 5,6,7

i.e. 6 goes back into the overflow menu! also you can never see tabs 4,5,6 next to each other

The tabs are now all rendered and scrolled into position, so tabs stay in their position relative to the other tabs,
 you can also use the mouse wheel to scroll the tabs:

tabs    | overflow menu
1,2,3,4 | 5,6,7

selecting 6 from overflow menu would give:

3,4,5,6 | 1,2,7    i.e 6 is scrolled into view

selecting 3 would then leave it the same, since 3 is already in view

Actually what is shown is the full tabset shifted to show the current tab:

clipped left | showing | clipped right
        1,2 | 3,4,5,6 | 7

This now works more like the tabs in other applications, like VSCode for example.

So in your case the tabs are clipped, showing the end of the last tab, not sure about the spacing after the tab, 
but there is a bit of space added to allow for the size of the overflow menu number.

**Comment by edemaine** [comment]
Ah, I see now.  I did notice the scrollability and wondered if that was the intent.  Thanks for the explanation!

I can update my tooltip on the overflow button to describe this behavior.  (Of possibly more general interest: the `icons` setting lets you put react-bootstrap `<OverlayTrigger>`s around custom icons, which makes it easy to add tooltips to built-in buttons.)

A funny thing is that, when the window is too narrow to show the selected tab title, the overflow button lists the selected tab too.  I guess this is the right behavior.

Is it possible for the selected tab button to be **left justified** instead of right justified?  That would be more intuitive behavior to me, when the layout has small width or the tabs have long titles; I usually care more about the beginning of the tab title, not the end.

For example, here is what I see in a one-tab tabset, on initial load or when selecting the tab from the "overflow tabs" list:

![image](https://user-images.githubusercontent.com/2218736/113311117-f40bc200-92d6-11eb-83c8-08086e8d80d4.png)

I would rather see this: (which I can get to by scrolling)

![image](https://user-images.githubusercontent.com/2218736/113311188-05ed6500-92d7-11eb-99a0-61fc44a54ab3.png)

Is this worth a configuration option, or changing the default behavior?  (It would only affect the case where one selected tab does not fit.)

**Comment by nealus** [comment]
Checked in a change that will align left when only one tab that is larger than the available space.

**Comment by edemaine** [comment]
Thanks &mdash; the new version seems to work great!
