### ISSUE TITLE
questions about design

### ISSUE THREAD

**Issue by yojona** [caplin/FlexLayout#211]
Hi, im a new user using FlexLayout.

1. Is there a good design reason for having to convert our model from json first, rather than just passing the JSON to FlexLayout, and then use Model.FromJson internally? Why add an extra step to implementation?
2.  Why do we need the factory? I would like to have components in my json model, like:

```javascript
{...
          "children": [
            {
              "type": "tab",
              "name": "One",
              "component": <div>Hi everyone!</div>
            }
          ]
        },
}
```

**Comment by LoganDark** [comment]
> Why add an extra step to implementation?

Because that way you have the Model that you can manipulate as you please.

> Why do we need the factory? I would like to have components in my json model, like:

For serialization. Basically the component is the serialized name of your component, you store any persistent state in tab config. That way when you save it, all important state is saved, and when you load it, the factory can recreate the component & the component will properly read from state

**Comment by yojona** [comment]
Fair enough, thanks
