### ISSUE TITLE
Tabsets resizing

### ISSUE THREAD

**Issue by 22uts** [caplin/FlexLayout#316]
### Describe the bug

Hello, I would like to know if the behavior below can be enabled by configuration or if it can be implemented.

From the demo site with 3 tabsets, I would like to resize the first tabset from left using the splitter of the right tabset.  But as you can see on the image below, the splitter is bloqued by the width of first tabset.

### Steps to Reproduce the Bug or Issue

1. Create 3 tabsets (https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/demo/index.html with headers template)
2. Grab the right splitter
3. Slide the splitter to the left side

### Expected behavior

The first tabset to be resized while using the splitter of the right tabset.

### Operating System

-

### Browser Type?

Chrome

### Browser Version

100

### Screenshots or Videos

![tab-resinzing](https://user-images.githubusercontent.com/104089618/164276830-16e623c9-dabd-4077-9a11-b1fe99aba54b.gif)

### Additional context

Can we achieve that ?

**Comment by nealus** [comment]
No, sorry, the splitter cannot do that

**Comment by 22uts** [comment]
OK. Thanks for the answer.

**Comment by myklt** [comment]
Hi @nealus ,

is it not possible to implement proportionally shrinking tabsets (as shown above) due to some architectural limitation or this library simply does not have this feature, but it practically could be implemented? I'm looking into `react-mosaic` and there they have such feature, but `FlexLayout` in general is much more advanced, so it would be good to have also shrinking tabsets feature. I would be happy to contribute, if you think it is doable using splitter.

**Comment by nealus** [comment]
it is certainly possible, I don't think it would be too difficult. If you would like to contribute that would be great.
